### PR TITLE
Add multiple loop support

### PR DESCRIPTION
**Pull request by Fenyutanchan**
Now it could resolve the process seed YAML format as
```YAML
...
n_loop: 0-3, 5-9, 10:12
...
```

### CODE REVIEW

**Review by zhaoli-IHEP — COMMENTED** [review]
It is not good to mix up different loops. 
Works for different loops should decouple.

**Review by zhaoli-IHEP — COMMENTED** [review]
It is not good idea to use String for n_loop.

**Comment by Fenyutanchan** [comment]
> It is not good to mix up different loops.
> Works for different loops should decouple.

No, they will not be mixed up.
They will be collected as
```log
b_g_TO_Wminus_t
├── b_g_TO_Wminus_t_0Loop
│   ├── b_g_TO_Wminus_t.yaml
│   ├── b_g_TO_Wminus_t_0Loop_amplitudes
│   ├── b_g_TO_Wminus_t_0Loop_visuals
│   └── sm_CKMdiag_Haa.log
├── b_g_TO_Wminus_t_1Loop
│   ├── b_g_TO_Wminus_t.yaml
│   ├── b_g_TO_Wminus_t_1Loop_amplitudes
│   ├── b_g_TO_Wminus_t_1Loop_visuals
│   └── sm_CKMdiag_Haa.log
└── b_g_TO_Wminus_t_2Loop
    ├── b_g_TO_Wminus_t.yaml
    ├── b_g_TO_Wminus_t_2Loop_amplitudes
    ├── b_g_TO_Wminus_t_2Loop_visuals
    └── sm_CKMdiag_Haa.log

10 directories, 6 files
```

**Comment by Fenyutanchan** [comment]
> 

Ehh, `String` or `Int` are all supported.

**Comment by Fenyutanchan** [comment]
```YAML
# input file for calculation details
# model related information

# model name
model_name: "sm_CKMdiag_Haa"

# use unitary_gauge for internal vector boson
unitary_gauge: true

# content of "quark-parton", the "parton" will also contain gluon. Only for seed program.
#const partons = Array{String,1}( [ "g", "u", "d", "ubar", "dbar", "s", "c", "b", "sbar", "cbar", "bbar" ] )   
# for single top @ NNLO
#const partons = Array{String,1}( [ "g", "u", "d", "ubar", "dbar", "b", "bbar" ] )   
# for Higgs+Jet @ NLO
partons: [ "g", "u", "ubar", "d", "dbar", "b", "bbar" ]

# only for seed program
AllowLeptonNumberViolation: false
AllowQuarkGenerationViolation: false

# process information
DropTadpole: true              # drop tadpole?
DropWFcorrection: true         # drop WFcorrection?

# number of loops
n_loop: 0-2
# order of QCD counter-term vertices
QCDCT_order: 0

# order of QCD coupling gs in the amplitude
Amp_QCD_order: "2*n_loop" 
# order of QED coupling ee in the amplitude
Amp_QED_order: 1 
# order of special coupling in the amplitude
Amp_SPC_order: 0 

# min ep power in the amplitude
Amp_Min_Ep_Xpt: "-2*n_loop"
# max ep power in the amplitude
Amp_Max_Ep_Xpt: 0

# incoming and outgoing information
incoming: [ "dbar", "u" ]          # incoming particles
outgoing: [ "Wplus" ]               # outgoing particles 

# Symmetry configuration
symmetry: []
```
I mean that one could run `digest_seed_proc("/path/to/this.yaml")` directly.

**Comment by zhaoli-IHEP** [comment]
> > It is not good idea to use String for n_loop.
> 
> Ehh, `String` or `Int` are all supported.

No, it is better to stick on Int. It is not necessary to make the code complicated.

**Pull request closed without merging**
